=== kaspervandenberg/aida/Search/zylabPatisClient/src/main/xsd/zylabPatisClientConfig.xsd
<?xml version="1.0"?>
<!-- Â© Maastro, 2013 -->

<!--
	Configuration options for ZylabPatisClient java class in package 
	nl.maastro.eureca.aida.search.zylabpatisclient.
-->

<xs:schema version="1.0"
					 xmlns:xs="http://www.w3.org/2001/XMLSchema"
					 xmlns="http://search.aida.eureca.maastro.nl/zylabpatisclient/config"
					 targetNamespace="http://search.aida.eureca.maastro.nl/zylabpatisclient/config"
					 elementFormDefault="qualified">


<!--
	Index to search can be either a webservice or a local directory with indexes. 
-->		
<xs:complexType name="IndexLocation">
	<xs:choice>
		<xs:element name="webservice" type="ServiceCall" />
		<xs:element name="localIndex" type="FileUrl" />
	</xs:choice>	
</xs:complexType>

<!--
	Address of a FileUrl must be the URL of a directory where a Lucene index is 
	stored.  The configured URL must be locally accessible.
-->
<xs:complexType name="FileUrl">
	<xs:attribute name="file" type="xs:anyURI" use="required" />
</xs:complexType>

<!--
	A Service is accessed via its URL and requires an index to search in.
-->			
<xs:complexType name="ServiceCall">
	<xs:attribute name="address"
								type="xs:anyURI" 
								default="http://clinisearch.ad.maastro.nl/axis/services/SearcherWS" />

	<xs:attribute name="index"
								type="xs:string"
								default="Zylab_test-20130415-02" />
</xs:complexType>
		
<!--
	Name of a field as it exists in the lucene index
-->
<xs:complexType name="FieldName">
	<xs:attribute name="field" type="xs:string" default="content" />
</xs:complexType>


<xs:complexType name="HitCount">
	<xs:attribute name="nHits" type="xs:nonNegativeInteger" default="1000" />
</xs:complexType>

<!--
	Query that clients of the Zylab Patis Search Client can refer to by id
-->
<xs:complexType name="ConceptQuery">
	<xs:simpleContent>
		<xs:extension base="xs:string">
			<xs:attribute name="id" type="xs:QName" use="required" />
		</xs:extension>
	</xs:simpleContent>
</xs:complexType>

<!--
	A JSON file that provides a collection of patients mapped to their expected 
	trial eligibilty criterion.
-->
<xs:complexType name="PatisJsonSource">
	<xs:attribute name="file" type="xs:anyURI" use="required"/>	
	<xs:attribute name="concept-ref" type="xs:QName" use="required" />
</xs:complexType>
	
<xs:element name="zylabPatisClientConfig">
	<xs:complexType>
		<!--
			Configure the Zylab Patis Search Client by specifying any number of the 
			elements below, and in any order.  When an element occurs multiple times,
			Zylab Patis Search Client uses the last value.  When no value is 
			configured the Zylab Patis Search Client uses a default setting.
		-->
		<xs:sequence minOccurs="0" maxOccurs="unbounded">
			<xs:choice>
				<!--
					Location of the index to use.  By default the webservice at
					http://clinisearch.ad.maastro.nl/axis/services/SearcherWS is used.
				-->
				<xs:element name="index" type="IndexLocation" />

				<!--
					Lucene index field name to use for query terms without field 
					specification.  By default the "content" is used
				-->
				<xs:element name="defaultField" type="FieldName" />

				<!--
					The used Lucene API requires specifying the maximum number of search
					results that it will return.  Note that the Zylab Patis Search Client
					will issue multiple queries when searching a list of Patis numbers,
					the maximum number of results that it returns might exceed the 
					configured 'resultLimit'.
				-->
				<xs:element name="resultLimit" type="HitCount" />

				<xs:element name="patients" type="PatisJsonSource" />
				
				<xs:element name="query" type="ConceptQuery" />
			</xs:choice>
		</xs:sequence>

		<!--
			Zylab Patis Search Client will check whether the configuration matches
			the version it expects.
		-->
		<xs:attribute name="version" type="xs:string" fixed="${project.version}" />
		
	</xs:complexType>		
</xs:element>

</xs:schema>
<!-- vim: set tabstop=2 shiftwidth=2 : -->

=== kaspervandenberg/aida/Search/search/src/main/resources/testConfig.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
To change this template, choose Tools | Templates
and open the template in the editor.
-->


<zylabPatisClientConfig
	xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
	xmlns='http://search.aida.eureca.maastro.nl/zylabpatisclient/config'
	xmlns:zpsc='http://search.aida.eureca.maastro.nl/zylabpatisclient/config'
	xsi:schemaLocation='http://search.aida.eureca.maastro.nl/zylabpatisclient/config file:/home/kasper2/git/aida.git/Search/search/src/main/xsd/zylabPatisClientConfig.xsd'
	>
	
	<index>
<?ignore
		<webservice address="http://vocab.maastro.nl/axis/serBlablafdvices/SearcherWS" index="Zylab_test-2013bla0415-02"></webservice>
?>
		<localIndex file="file:///tmp/file" />	
	</index>
<?ignore
	<index>
		<webservice address="http://other.org/ws" />
	</index>
?>
	<defaultField field=".ktnje" />
	<resultLimit nHits="1203" />
	<query id="zpsc:ewrt">Bla bla</query>
	<query id="eewrt">Bla bla</query>

</zylabPatisClientConfig>

=== kaspervandenberg/aida/Search/zylabPatisClient/src/main/webapp/WEB-INF/zpsc-config.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
To change this template, choose Tools | Templates
and open the template in the editor.
-->


<zylabPatisClientConfig
	xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
	xmlns='http://search.aida.eureca.maastro.nl/zylabpatisclient/config'
	xmlns:zpsc='http://search.aida.eureca.maastro.nl/zylabpatisclient/config'
	xmlns:vocab='http://vocab.maastro.nl/zylabPatisClient/zpsc/queryPattern'
	xsi:schemaLocation='http://search.aida.eureca.maastro.nl/zylabpatisclient/config file:/home/kasper2/git/aida.git/Search/search/src/main/xsd/zylabPatisClientConfig.xsd'
	>
	
	<index>
<?ignore
		<webservice address="http://vocab.maastro.nl/axis/serBlablafdvices/SearcherWS" index="Zylab_test-2013bla0415-02"></webservice>
?>
		<localIndex file="file:///var/local/aida/indexes/Zylab_test-20130415-02" />	
	</index>
<?ignore
	<index>
		<webservice address="http://other.org/ws" />
	</index>
?>
	<defaultField field="content" />
	<resultLimit nHits="1000" />
	<query id="zpsc:scopedQuery1">This can be some content parsable by Lucence's query parser</query>
	<query id="unscopedQuery2">Query string for unscoped query</query>
	<query id="vocab:longparenchym">longparenchym</query>
	<query id="vocab:empty"> </query>
	

</zylabPatisClientConfig>

<!-- vim: set tabstop=2 shiftwidth=2 :-->

=== kaspervandenberg/aida/Search/zylabPatisClient/src/main/resources/zpsc-config.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
	This xml file should be processed by Maven's resources plugin.  Which replaces
	${â€¦} with property values defined in the pom.
-->


<zylabPatisClientConfig
	xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
	xmlns='http://search.aida.eureca.maastro.nl/zylabpatisclient/config'
	xmlns:zpsc='http://search.aida.eureca.maastro.nl/zylabpatisclient/config'
	xmlns:vocab='http://clinisearch.ad.maastro.nl/zylabpatis/'
	xmlns:pcq='http://clinisearch.ad.maastro.nl/zylabpatis/'
	xmlns:local='http://localhost:8080/zylabPatisClient/zpsc/queryPattern/'
	xsi:schemaLocation='http://search.aida.eureca.maastro.nl/zylabpatisclient/config file:/home/kasper/git/aida.git/Search/search/src/main/xsd/zylabPatisClientConfig.xsd'
	>
	
	<index>
		<localIndex file="file://${aida.indexdir}/${aida.index}" />

		<!-- Examples of indexes -->
<?ignore
		<webservice address="http://clinisearch.ad.maastro.nl/axis/services/SearcherWS" index="Zylab_test-20130415-02"></webservice>
		<localIndex file="file:///var/local/aida/indexes/Zylab_test-20130602" />	
		<localIndex file="file:///home/kasper2/mnt/aida/indexes/Zylab_test-20130602" />	
		<localIndex file="file:///home/kasper/tmp/vocab/aida/Zylab_test-20130602" />	
		<localIndex file="file:///home/kasper/tmp/vocab/aida/indexes/Zylab_test-20130602" />	
		<webservice address="http://other.org/ws" />
?>
	</index>

	<defaultField field="content" />
	<resultLimit nHits="1000" />
<!-- Lists of patients and data to validate a concept query-->
	<patients concept-ref="pcq:metastasis" file="file://${aida.validationdata.metastasis}" />
	<patients concept-ref="pcq:chemokuur" file="file://${aida.validationdata.chemo}" />

<!-- Examples of lists of patients and data to validate a concept query -->
<?ignore
	<patients concept-ref="pcq:metastasis" file="file:///home/kasper/git/aida.git/Search/zylabPatisClient/data/patients-metastasis-20121221_AD2.json" />
	<patients concept-ref="pcq:chemokuur" file="file:///home/kasper/git/aida.git/Search/zylabPatisClient/data/patients-chemo-20121221_AD2.json" />
?>

<!-- Examples of queries, currently unused -->
<?ignore
	<query id="zpsc:scopedQuery1">This can be some content parsable by Lucence's query parser</query>
	<query id="unscopedQuery2">Query string for unscoped query</query>
	<query id="vocab:longparenchym">longparenchym</query>
	<query id="local:longparenchym">longparenchym</query>
	<query id="vocab:empty"> </query>
?>
	

</zylabPatisClientConfig>

<!-- vim: set tabstop=2 shiftwidth=2 :-->
